apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: psm3nnpc9-python
  janus-idp.io/tekton: psm3nnpc9-python
  backstage.io/kubernetes-id: psm3nnpc9-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: psm3nnpc9-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
